KyleGru/sports-squares

- public/js/game.js
- views/game.handlebars
- views/homepage.handlebars
Created homepage.hadlebars, game.handlebars, and created a game.js in the public folder to create the game board.
> game board creation

- controllers/api/index.js
- controllers/api/sportFetch.js
- public/js/game.js
- server.js
The data from the sports api is now accessible on the front end via the browser.
> Add sports api fetch for frontend access

- controllers/api/sportFetch.js
- public/js/game.js
Console log needed data to begin working on transferring it into the html
> Pull quarter, team, and score data from api to console

- public/js/game.js
- views/game.handlebars
Score, team, and quarter info is now displayed in the html.
> Add game info to html

- package-lock.json
- package.json
- public/js/game.js
- public/stylesheets/style.css
- views/game.handlebars
- views/layouts/main.handlebars
> Handlebars 2

- views/game.handlebars
Added team, score, and quarter info into game html.
> Add sport info into html

- controllers/api/gamesAvailable.js
- controllers/api/index.js
- controllers/api/sportFetch.js
- models/games.js
- models/index.js
- package-lock.json
- package.json
- public/js/game.js
- views/game.handlebars
Choice are now rendered which enable the user to choose which game info to display based on the date.
> Select game functionality

- controllers/api/gameDateInfo.js
- controllers/api/gamesAvailable.js
- controllers/api/index.js
- controllers/api/sportFetch.js
- models/gameDates.js
- models/index.js
- public/js/game.js
- views/game.handlebars
Games from the current data will now display automatically and will be responsive to the dates changing.
> Adjust fetch to get game data automatically based on current date

- public/js/game.js
- views/game.handlebars
Added some styling to game choice buttons.
> Add game button css

- controllers/api/gameDateInfo.js
- controllers/api/gamesAvailable.js
- controllers/api/sportFetch.js
- public/js/game.js
- public/js/login.js
- views/game.handlebars
Usernames can be added to boxes now and the api links have been updated for Heroku.
> Usernames in boxes and api fix

- public/js/game.js
- public/js/login.js
- views/game.handlebars
Users can enter a name in the form box to switch between names to put into squares.
> Add form for switching usernames

- public/js/game.js
Function to refresh score periodically.
> Add score refresh function

- public/js/game.js
Clear button will now change the text and color of background back to original colors.
> Adjust clear button to reset squares

- controllers/api/gameDateInfo.js
- controllers/api/gamesAvailable.js
- controllers/api/sportFetch.js
- public/js/game.js
Game won't render null scores or info now.
> Adjust render game logic and set api key

- public/js/game.js
- public/stylesheets/style.css
- views/game.handlebars
Fixes bug that refreshes multiple games simultaneously.
> Fix refresh bug

- public/js/game.js
- views/game.handlebars
Score is now available on score board by quarter.
> Score now live updates in score board

- controllers/api/gameDateInfo.js
- controllers/api/gamesAvailable.js
- controllers/api/sportFetch.js
- public/js/game.js
Random number generator no longer generates duplicates in each team section.
> Numbers generate only one of each number per team

- controllers/api/gameDateInfo.js
- controllers/api/gamesAvailable.js
- controllers/api/sportFetch.js
- public/js/game.js
- public/stylesheets/style.css
- views/game.handlebars
Game data can now persist after refreshing page and a reset function has been added.
> Save sqaure data

- public/js/game.js
- public/stylesheets/style.css
- views/game.handlebars
Game page error now visible if user attempts to click a square without any username available.
> Add error msg if box is selected without username

- public/stylesheets/style.css
Added more css to buttons on game page.
> Button css

- controllers/api/gameDateInfo.js
- controllers/api/gamesAvailable.js
- controllers/api/sportFetch.js
- public/js/game.js
- public/stylesheets/style.css
- views/game.handlebars
Add board for tacking users, number of squares clicked, and the amount wagered based on the set multiplier. Also made many elements conditionally rendered.
> Gameplay features
